# 服务监听地址
addr: 127.0.0.1:5678

# 是否开启debug模式
debug: false

# 是否开启认证
auth:
  enable: false
  # 认证用户名
  username: admin
  # 认证密码
  password: 123456

# 搜索引擎部分
engine:
  # 数据存放路径
  data: ./data
  # 词库路径
  dictionary: ./dictionary

  # 文件分块
  shard: 5

  # 索引队列最大值
  queue_max: 1000

  # GC时间间隔
  gc_interval: 10
